<?php

// Copyright (C) 2010-2026, the Friendica project
// SPDX-FileCopyrightText: 2010-2026 the Friendica project
//
// SPDX-License-Identifier: AGPL-3.0-or-later

$platforms = [
	'AlphaChat'                                              => 'alphachat',
	'AV Arcade'                                              => 'av-arcade',
	'BaseKit'                                                => 'basekit',
	'BBEdit'                                                 => 'bbedit',
	'Big Cartel'                                             => 'big-cartel',
	'Blogger'                                                => 'blogger',
	'Bloom'                                                  => 'bloom',
	'Bludit'                                                 => 'bludit',
	'BunnyPress'                                             => 'bunnypress',
	'Contao Open Source CMS'                                 => 'contao',
	'castopod'                                               => 'castopod',
	'cgit'                                                   => 'cgit',
	'Chevereto'                                              => 'chevereto',
	'ClanSphere'                                             => 'clansphere',
	'Claudia Content'                                        => 'claudia-content',
	'diaspora'                                               => 'diaspora',
	'DIMV'                                                   => 'dimv',
	'Discourse'                                              => 'discourse',
	'Divi'                                                   => 'divi',
	'Django-cypress'                                         => 'django-cypress',
	'Docutils'                                               => 'docutils',
	'DokuWiki'                                               => 'dokuwiki',
	'Drupal'                                                 => 'drupal',
	'Element'                                                => 'element',
	'Eleventy'                                               => 'eleventy',
	'filerun'                                                => 'filerun',
	'FlatPress'                                              => 'flatpress',
	'Gatsby'                                                 => 'gatsby',
	'Ghost'                                                  => 'ghost',
	'gitweb'                                                 => 'gitweb',
	'gnusocial'                                              => 'gnusocial',
	'Government Site Builder'                                => 'government-site-builder',
	'GravCMS'                                                => 'gravcms',
	'grocy'                                                  => 'grocy',
	'Gruta'                                                  => 'gruta',
	'hakyll'                                                 => 'hakyll',
	'HedgeDoc - Collaborative markdown notes'                => 'hedgedoc',
	'Hello, world. https://github.com/mimecuvalo/helloworld' => 'helloworld',
	'Hexo'                                                   => 'hexo',
	'Hugo'                                                   => 'hugo',
	'ian'                                                    => 'ian',
	'InterRed'                                               => 'interred',
	'Ikiwiki'                                                => 'ikiwiki',
	'Jekyll'                                                 => 'jekyll',
	'Joomla!'                                                => 'joomla',
	'KeyHelp'                                                => 'keyhelp',
	'Known https://withknown.com'                            => 'known',
	'KONTEXT-CMS (c) WARENFORM [www.warenform.net]'          => 'kontext-cms',
	'ktistec'                                                => 'ktistec',
	'lemoncurry'                                             => 'lemoncurry',
	'LibreOffice'                                            => 'libreoffice',
	'Magazine News Byte'                                     => 'magazine-news-byte',
	'Magnet'                                                 => 'magnet',
	'mastodon'                                               => 'mastodon',
	'Mattermost'                                             => 'mattermost',
	'MediaWiki'                                              => 'mediawiki',
	'Medium'                                                 => 'medium',
	'microblog'                                              => 'microblog',
	'Misskey'                                                => 'misskey',
	'Mobirise'                                               => 'mobirise',
	'Movable Type Pro'                                       => 'movable-type',
	'Movim'                                                  => 'movim',
	'MyArcadePlugin Pro'                                     => 'my-arcade-plugin',
	'Nanoc'                                                  => 'nanoc',
	'nb3 system v1.6'                                        => 'nb3',
	'Nikola (getnikola.com)'                                 => 'nikola',
	'Odoo'                                                   => 'odoo',
	'Org mode'                                               => 'org-mode',
	'Org-mode'                                               => 'org-mode',
	'Org Mode'                                               => 'org-mode',
	'Osclass'                                                => 'osclass',
	'pamphlets/vinyl-press'                                  => 'pamphlets',
	'peertube'                                               => 'peertube',
	'phpMyFAQ'                                               => 'phpmyfaq',
	'Pelican'                                                => 'pelican',
	'pH7CMS,'                                                => 'ph7cms',
	'Polr'                                                   => 'polr',
	'Publii Open-Source CMS for Static Site'                 => 'publii',
	'pygruta'                                                => 'pygruta',
	'Riot'                                                   => 'riot',
	'Satelito'                                               => 'satelito',
	'Scully'                                                 => 'scully',
	'Sedo'                                                   => 'sedo',
	'sitebaker'                                              => 'sitebaker',
	'SitePad'                                                => 'sitepad',
	'SMAR'                                                   => 'smar',
	'SPIP'                                                   => 'spip',
	'STUDIO'                                                 => 'studio',
	'Synology - Synology DiskStation'                        => 'synology',
	'Thufie'                                                 => 'thufie',
	'TiddlyWiki'                                             => 'tiddlywiki',
	'Typesetter CMS'                                         => 'typesetter',
	'TYPO3 CMS'                                              => 'typo3',
	'Tumblr'                                                 => 'tumblr',
	'Typecho'                                                => 'typecho',
	'http://txt2tags.org'                                    => 'txt2tags',
	'UISP'                                                   => 'uisp',
	'VuePress'                                               => 'vuepress',
	'webEdition CMS'                                         => 'webedition',
	'Webflow'                                                => 'webflow',
	'WikkaWiki'                                              => 'wikkawiki',
	'Wix.com'                                                => 'wix.com',
	'WordPress.com'                                          => 'wordpress',
	'WordPress'                                              => 'wordpress',
	'Write.as'                                               => 'write.as',
	'XAG/CMS'                                                => 'xagcms',
	'Zim'                                                    => 'zim',
];

$ap_platforms = [
	'honk'     => 'honk',
	'PeerTube' => 'peertube',
];

$dfrn_platforms = [
	'Friendika' => 'friendika',
	'Friendica' => 'friendica',
];

$zap_platforms = [
	'hubzilla' => 'hubzilla',
	'osada'    => 'osada',
];

return [
	'ap_platforms'   => $ap_platforms,
	'dfrn_platforms' => $dfrn_platforms,
	'zap_platforms'  => $zap_platforms,
	'platforms'      => $platforms,
];
